<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE glossary [
  <!ELEMENT staterotation   (rotation+)>
  <!ELEMENT rotation        (state, banner)>
  <!ELEMENT state           (#PCDATA)>
  <!ELEMENT banner          (#PCDATA)>
]>
<staterotation>
	
	<rotation>
	  <state>ca</state> 
	  <banner>8</banner> 
	</rotation> 
	
	<rotation>
	  <state>hi</state> 
	  <banner>1</banner> 
	</rotation>
	
	<rotation>
	  <state>fl</state> 
	  <banner>2</banner> 
	</rotation>
	
	<rotation>
	  <state>tx</state> 
	  <banner>4</banner> 
	</rotation>
	
	<rotation>
	  <state>ny</state> 
	  <banner>6</banner> 
	</rotation>

</staterotation>


